/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import sem1.DoSuborov;
import sem1.Hospitalizacia;
import sem1.Nemocnica;
import sem1.Pacient;
import sem1.Program;

/**
 *
 * @author davidecek
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private Program program;

    public GUI() {
        program = new Program();
        initComponents();
        LocalDate date = LocalDate.now();
        local_date.setDate(convert(date));

    }

    private static LocalDate convert(Date date) {
        return date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }

    private static Date convert(LocalDate localDate) {
        return Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        Hospitalizacie = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nazov_nem = new javax.swing.JTextField();
        find_butt = new javax.swing.JButton();
        insert_butt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hosp_nemocnice = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        rodnecislo = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        diagnoza = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        datum_nar = new org.jdesktop.swingx.JXDatePicker();
        rodne_cislo = new javax.swing.JFormattedTextField();
        kod_ZP = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        meno = new javax.swing.JTextField();
        priezvisko = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_nadpis = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pacienti = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nazov_nem_field = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nazovN1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nazovN2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nazovN = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        nemo = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        poist_spinn = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        odDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel23 = new javax.swing.JLabel();
        doDate = new org.jdesktop.swingx.JXDatePicker();
        jButton11 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        mesiacNadpis = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        mesSP = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        rokSp = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        poistVypis = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        local_date = new org.jdesktop.swingx.JXDatePicker();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 600));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Pridavanie Hospitalizacie");

        jLabel14.setText("Nazov Nemocnice");

        nazov_nem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        find_butt.setText("Najd akt. pacientov nemocnice");
        find_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_buttActionPerformed(evt);
            }
        });

        insert_butt.setText("Zacni Hospitalizaciu");
        insert_butt.setMaximumSize(new java.awt.Dimension(131, 23));
        insert_butt.setMinimumSize(new java.awt.Dimension(131, 23));
        insert_butt.setPreferredSize(new java.awt.Dimension(131, 23));
        insert_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttActionPerformed(evt);
            }
        });

        hosp_nemocnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(hosp_nemocnice);

        jLabel17.setText("Rodne Cislo pacienta");

        try {
            rodnecislo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rodnecislo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Diagnoza");

        jButton7.setText("Ukonci Hospitalizaciu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazov_nem)
                            .addComponent(rodnecislo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(diagnoza)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insert_butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(find_butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazov_nem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rodnecislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(diagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(insert_butt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(find_butt)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        Hospitalizacie.addTab("Hospitalizacie", jPanel3);

        try {
            rodne_cislo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rodne_cislo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rodne_cislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rodne_cisloActionPerformed(evt);
            }
        });

        jLabel2.setText("Meno");

        jLabel3.setText("Priezvisko");

        jLabel4.setText("Rodne cislo");

        jLabel5.setText("Datum narodenia");

        jLabel6.setText("Kod zdravotnej poistovne");

        meno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        meno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoActionPerformed(evt);
            }
        });

        priezvisko.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pridavanie pacientov");

        text_nadpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        text_nadpis.setText("Pacienti");

        jButton1.setText("Vloz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pacienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pacienti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacientiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pacienti);

        jButton2.setText("daj vsetkych akt. hosp. pacientov nemocnice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Vyhladaj pacienta v nemocnici :");

        jButton6.setText("Vyhladaj zaznamy pacienta podla RC");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Vyhladaj zaznamy pacienta podla Mena");
        jButton5.setActionCommand("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(150, 150, 150)
                            .addComponent(meno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(datum_nar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(rodne_cislo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(kod_ZP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(nazov_nem_field)))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(text_nadpis)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(127, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_nadpis))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rodne_cislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datum_nar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kod_ZP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nazov_nem_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        Hospitalizacie.addTab("Pacienti", jPanel2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Presun Nemocnice");

        jLabel20.setText("Nazov Nemocnice");

        nazovN1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel21.setText("Nazov Novej Nemocnice");

        nazovN2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton10.setText("<     Presun Agendu     >");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(nazovN1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(nazovN2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton10)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(nazovN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(nazovN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Hospitalizacie.addTab("Presun Nemocnice", jPanel4);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pridavanie Nemocnic");

        jLabel9.setText("Nazov Nemocnice");

        nazovN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton3.setText("pridat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nemo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(nemo);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nemocnice");

        jButton4.setText("najdi vsetky nemocnice podla nazvu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setText("Najdi pacientov nemocnice danej poistovne");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel15.setText("Poistovna");

        jLabel22.setText("od");

        jLabel23.setText("do");

        jButton11.setText("najdi hosp. pacientov v intervale");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addComponent(jButton9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jButton3)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel9)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(1, 1, 1)
                                                                        .addComponent(jLabel15)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(nazovN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(poist_spinn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel22)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(odDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel23)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(doDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12)))))
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton11)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nazovN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(59, 59, 59)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(poist_spinn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(doDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        Hospitalizacie.addTab("Nemocnice", jPanel1);

        mesiacNadpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mesiacNadpis.setText("Mesiac ");

        jLabel26.setText("Mesiac");

        jButton8.setText("zobraz");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel27.setText("Rok");

        poistVypis.setColumns(20);
        poistVypis.setRows(5);
        jScrollPane5.setViewportView(poistVypis);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(47, 47, 47)
                                .addComponent(rokSp))
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(33, 33, 33)
                                .addComponent(mesSP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mesiacNadpis)
                        .addGap(442, 442, 442))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(mesiacNadpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mesSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(rokSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Hospitalizacie.addTab("Poistovna", jPanel6);

        jLabel19.setText("Lokalny datum");

        jButton12.setText("generujData");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("uloz");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("nacitaj");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hospitalizacie, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(local_date, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(local_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hospitalizacie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<Nemocnica> nemocnice = null;
        nemocnice = program.dajVsetkyNemocnice();

        if (nemocnice != null) {
            DefaultTableModel dtm = new DefaultTableModel();
            String col[] = {"Nazov", "Ulica", "Mesto"};
            dtm = new DefaultTableModel(col, 0);
            Object[] rowData = new Object[3];
            for (Nemocnica nemocnica : nemocnice) {
                rowData[0] = nemocnica.getNemocnica();
                dtm.addRow(rowData);
            }
            this.nemo.setModel(dtm);
            dtm.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(null, "Neexistuju ziadne nemocnice");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nazov = nazovN.getText();
        if (!nazov.equals("")) {
            program.vlozNovuNemocnicu(nazov);
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<Pacient> pacienti = null;
        String nazovNem = nazov_nem_field.getText();
        if (!nazovNem.equals("")) {
            pacienti = program.dajVsetkychPacientovNemocnice(nazovNem);
            if (pacienti != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Meno", "Priezvisko", "Rodne Cislo", "Datum Narodenia", "kod ZP"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[5];
                for (Pacient pacient : pacienti) {
                    rowData[0] = pacient.getMeno();
                    rowData[1] = pacient.getPriezvisko();
                    rowData[2] = pacient.getRodnecislo();
                    rowData[3] = pacient.getDatum_narodenia();
                    rowData[4] = pacient.getKod_ZP();
                    dtm.addRow(rowData);
                }
                this.pacienti.setModel(dtm);
                dtm.fireTableDataChanged();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String menoP = meno.getText();
        String priezvP = priezvisko.getText();
        String rc = rodne_cislo.getText();
        LocalDate date = convert(datum_nar.getDate());
        int kodZP = (Integer) kod_ZP.getValue();
        if (!menoP.equals("") && !priezvP.equals("") && !rc.equals("      /    ")) {
            program.vlozNovehoPacienta(menoP, priezvP, rc, date, kodZP);
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void rodne_cisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rodne_cisloActionPerformed
        try {
            MaskFormatter mask = new MaskFormatter("######/####");
            rodne_cislo = new JFormattedTextField(mask);
        } catch (ParseException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rodne_cisloActionPerformed

    private void find_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_buttActionPerformed
        String nazovNem = nazov_nem.getText();
        ArrayList<Pacient> pacienti = null;
        pacienti = program.najdiPacientovNemocnice(nazovNem);
        if (nazovNem.equals("")) {
            JOptionPane.showMessageDialog(null, "Nezadali nazov nemocnice");
        } else {
            if (pacienti != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Meno", "Priezvisko", "Rodne Cislo", "Datum Narodenia", "kod ZP"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[5];
                for (Pacient pacient : pacienti) {
                    rowData[0] = pacient.getMeno();
                    rowData[1] = pacient.getPriezvisko();
                    rowData[2] = pacient.getRodnecislo();
                    rowData[3] = pacient.getDatum_narodenia();
                    rowData[4] = pacient.getKod_ZP();
                    dtm.addRow(rowData);
                }
                this.hosp_nemocnice.setModel(dtm);
                dtm.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(null, "Pacienti neexistuju");
            }
        }
    }//GEN-LAST:event_find_buttActionPerformed

    private void insert_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttActionPerformed
        String nazovNem = nazov_nem.getText();
        String rod_cisl = rodnecislo.getText();
        LocalDate dat_zac = convert(local_date.getDate());
        String diag = diagnoza.getText();
        boolean prem = false;
        if (dat_zac != null && !nazovNem.equals("") && !rod_cisl.equals("      /    ")) {
            prem = program.zacniHospitalizaciuPacienta(nazovNem, rod_cisl, dat_zac, diag);
            if (prem == false) {
                JOptionPane.showMessageDialog(null, "Hospitalizacia uz existuje");
            } else {
                JOptionPane.showMessageDialog(null, "success");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }

    }//GEN-LAST:event_insert_buttActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String nazovNem = nazov_nem_field.getText();
        String rod_cislo = rodne_cislo.getText();
        if (!rod_cislo.equals("      /    ") && !nazovNem.equals("")) {
            Pacient pacient = program.najdiPacientaVNemocnici(nazovNem, rod_cislo);
            if (pacient == null) {
                JOptionPane.showMessageDialog(null, "Pacient neexistuje v nemocnici");
                return;
            }
            ArrayList<Hospitalizacia> hospitalizaciePacienta = null;
            hospitalizaciePacienta = pacient.getHospitalizacie();
            if (hospitalizaciePacienta == null) {
                JOptionPane.showMessageDialog(null, "Pacient nema hospitalizacie v nemocnici");
                return;
            }
            meno.setText(pacient.getMeno());
            priezvisko.setText(pacient.getPriezvisko());
            rodne_cislo.setText(pacient.getRodnecislo());
            datum_nar.setDate(convert(pacient.getDatum_narodenia()));
            kod_ZP.setValue(pacient.getKod_ZP());
            text_nadpis.setText("Hospitalizacie Pacienta:");
            if (hospitalizaciePacienta != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Datum zaciatku", "Datum konca", "Diagnoza"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[3];
                for (Hospitalizacia hospitalizacia : hospitalizaciePacienta) {
                    rowData[0] = hospitalizacia.getDatum_zac_hosp();
                    rowData[1] = "null";
                    if (hospitalizacia.getDatum_kon_hosp() != null) {
                        rowData[1] = hospitalizacia.getDatum_kon_hosp();
                    }
                    rowData[2] = hospitalizacia.getDiagnoza();
                    dtm.addRow(rowData);
                }
                this.pacienti.setModel(dtm);
                dtm.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(null, "Hospitalizacie pacienta neexistuju");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste vsetky potrebune udaje");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void menoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String nazovNem = nazov_nem_field.getText();
        String priezvisko = this.priezvisko.getText();
        String meno = this.meno.getText();
        if (!priezvisko.equals("") && !nazovNem.equals("") && !meno.equals("")) {
            ArrayList<Pacient> pacienti = null;
            pacienti = program.najdiPacientaVNemocniciPodlaMena(nazovNem, priezvisko, meno);
            ArrayList<Hospitalizacia> hospitalizaciePacienta = null;
            if (pacienti != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Meno", "Priezvisko", "Rodne Cislo", "Kod_ZP", "Datum Narodenia"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[5];
                for (Pacient pacient : pacienti) {
                    rowData[0] = pacient.getMeno();
                    rowData[1] = pacient.getPriezvisko();
                    rowData[2] = pacient.getRodnecislo();
                    rowData[3] = pacient.getKod_ZP();
                    rowData[4] = pacient.getDatum_narodenia();
                    dtm.addRow(rowData);
                }
                this.pacienti.setModel(dtm);
                dtm.fireTableDataChanged();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void pacientiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientiMouseClicked
        int row = pacienti.getSelectedRow();
        String r_c = (String) pacienti.getValueAt(row, 2);
        String nazovNem = nazov_nem_field.getText();
        Pacient pacient = program.najdiPacientaVNemocnici(nazovNem, r_c);
        ArrayList<Hospitalizacia> hospitalizaciePacienta = null;
        hospitalizaciePacienta = pacient.getHospitalizacie();
        new HospitalizaciePacienta(hospitalizaciePacienta).setVisible(true);

    }//GEN-LAST:event_pacientiMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nazovNem = nazov_nem.getText();
        String rod_cisl = rodnecislo.getText();
        LocalDate dat_zac = convert(local_date.getDate());
        boolean prem = false;
        if (dat_zac != null && !nazovNem.equals("") && !rod_cisl.equals("      /    ")) {
            prem = program.ukonciHospitalizaciuPacienta(nazovNem, rod_cisl, dat_zac);
            if (prem) {
                JOptionPane.showMessageDialog(null, "success");
            } else {
                JOptionPane.showMessageDialog(null, "hospitalizacia uz bola ukoncena");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ArrayList<Pacient> pacienti = null;
        String nazovNem = nazovN.getText();
        int poistovna = (Integer) poist_spinn.getValue();
        pacienti = program.dajPacientovNemocniceDanejPoistovne(nazovNem, poistovna);
        if (!nazovNem.equals("")) {
            if (pacienti != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Meno", "Priezvisko", "Rodne Cislo", "Datum Narodenia", "kod ZP"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[5];
                for (Pacient pacient : pacienti) {
                    rowData[0] = pacient.getMeno();
                    rowData[1] = pacient.getPriezvisko();
                    rowData[2] = pacient.getRodnecislo();
                    rowData[3] = pacient.getDatum_narodenia();
                    rowData[4] = pacient.getKod_ZP();
                    dtm.addRow(rowData);
                }
                this.nemo.setModel(dtm);
                dtm.fireTableDataChanged();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String nazovNem1 = nazovN1.getText();
        String nazovNem2 = nazovN2.getText();
        if (nazovNem1.equals("") || nazovNem1.equals("")) {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        } else {
            program.vymazNemocnicu(nazovNem1, nazovNem2);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        LocalDate odDatum = convert(odDate.getDate());
        String nazovNem = nazovN.getText();
        LocalDate doDatum = convert(doDate.getDate());
        ArrayList<Pacient> pacienti = null;

        if (!nazovNem.equals("") && doDatum != null && odDatum != null) {
            pacienti = program.dajHospPacientovVIntervale(nazovNem, odDatum, doDatum);
            if (pacienti != null) {
                DefaultTableModel dtm = new DefaultTableModel();
                String col[] = {"Meno", "Priezvisko", "Rodne Cislo", "Datum Narodenia", "kod ZP"};
                dtm = new DefaultTableModel(col, 0);
                Object[] rowData = new Object[5];
                for (Pacient pacient : pacienti) {
                    rowData[0] = pacient.getMeno();
                    rowData[1] = pacient.getPriezvisko();
                    rowData[2] = pacient.getRodnecislo();
                    rowData[3] = pacient.getDatum_narodenia();
                    rowData[4] = pacient.getKod_ZP();
                    dtm.addRow(rowData);
                }
                this.nemo.setModel(dtm);
                dtm.fireTableDataChanged();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        program.generujData();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int mesiac = (Integer) mesSP.getValue();
        LocalDate date = null;
        int rok = (Integer) rokSp.getValue();
        ArrayList<Pacient> pacienti = null;
        final String format = ("yyyy-MM-dd");

        date = LocalDate.parse(rok + "-" + mesiac + "-" + 14);

//        String mesiacN = 
//        mesiacNadpis.setText(mesiacN);
        LinkedList<String> vypis = program.dajPacientovVDniMesiaca(date);
        for (String poistovna : vypis) {
            poistVypis.append(poistovna);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        DoSuborov ds = new DoSuborov();
        ds.uloz(program);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        DoSuborov ds = new DoSuborov();
        ds.nacitaj(program);
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Hospitalizacie;
    private org.jdesktop.swingx.JXDatePicker datum_nar;
    private javax.swing.JTextField diagnoza;
    private org.jdesktop.swingx.JXDatePicker doDate;
    private javax.swing.JButton find_butt;
    private javax.swing.JTable hosp_nemocnice;
    private javax.swing.JButton insert_butt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JSpinner kod_ZP;
    private org.jdesktop.swingx.JXDatePicker local_date;
    private javax.swing.JTextField meno;
    private javax.swing.JSpinner mesSP;
    private javax.swing.JLabel mesiacNadpis;
    private javax.swing.JTextField nazovN;
    private javax.swing.JTextField nazovN1;
    private javax.swing.JTextField nazovN2;
    private javax.swing.JTextField nazov_nem;
    private javax.swing.JTextField nazov_nem_field;
    private javax.swing.JTable nemo;
    private org.jdesktop.swingx.JXDatePicker odDate;
    private javax.swing.JTable pacienti;
    private javax.swing.JTextArea poistVypis;
    private javax.swing.JSpinner poist_spinn;
    private javax.swing.JTextField priezvisko;
    private javax.swing.JFormattedTextField rodne_cislo;
    private javax.swing.JFormattedTextField rodnecislo;
    private javax.swing.JSpinner rokSp;
    private javax.swing.JLabel text_nadpis;
    // End of variables declaration//GEN-END:variables
}
